In [1]:
import torch

#### 문제 1

2D 텐서를 만들고 차원 0 위치에 크기가 1인 차원을 추가하세요.

In [2]:
x = torch.Tensor(2, 2)
print(x)

x = x.unsqueeze(0)
print(x)
print(x.shape)

tensor([[0., 0.],
        [0., 0.]])
tensor([[[0., 0.],
         [0., 0.]]])
torch.Size([1, 2, 2])


#### 문제 2 

이전 텐서에 추가한 차원을 삭제하세요.

In [3]:
x = x.squeeze(0)
print(x)
print(x.shape)

tensor([[0., 0.],
        [0., 0.]])
torch.Size([2, 2])


#### 문제 3

[3, 7) 범위를 갖는 5x3 크기의 랜덤한 텐서를 만드세요.

In [4]:
x = torch.rand(5, 3) * 4 + 3
print(x)

tensor([[4.2062, 6.2757, 4.6921],
        [5.6626, 5.7376, 5.8232],
        [3.8141, 5.0576, 6.2357],
        [6.3160, 3.9988, 5.7199],
        [6.3686, 5.7770, 6.1269]])


#### 문제 4

두 개의 2차원 행렬(`a=torch.rand(4,5)`, `b=torch.rand(5,4)`)의 행렬 곱셈(batch matrix-matrix product)을 계산하세요.

In [5]:
a = torch.rand(4, 5)
b = torch.rand(5, 4)
print(torch.mm(a, b))

tensor([[1.6304, 1.7976, 0.7759, 1.8891],
        [1.1925, 1.6433, 0.6062, 1.3114],
        [1.6762, 1.8343, 0.8535, 1.6334],
        [1.7336, 1.9356, 0.9333, 1.6556]])


#### 문제 5

문제 4에서 만든 행렬 a 의 각 열 별 덧셈을 수행해 벡터 vec 을 만듭니다. 결과 벡터의 길이는 행렬의 열의 길이와 같아야 합니다.
원본 행렬, 결과 벡터의 형상도 출력합니다.

In [6]:
v = a.sum(dim=0)
print(v)
print(a.shape)
print(v.shape)

tensor([3.1870, 1.7324, 2.5182, 2.0939, 2.0233])
torch.Size([4, 5])
torch.Size([5])


#### 문제 6

두 개의 2차원 행렬(`a=torch.rand(3,4,5)`, `b=torch.rand(3,5,4)`)의 배치 행렬 곱셈(batch matrix-matrix product)을 계산하세요.

In [8]:
a = torch.rand(3, 4, 5)
b = torch.rand(3, 5, 4)
c = torch.bmm(a, b)
print(c)
print(c.shape)

tensor([[[1.9679, 0.7372, 1.9469, 1.8146],
         [1.3571, 0.6023, 1.3267, 1.0715],
         [2.7989, 1.4277, 2.7934, 2.5841],
         [1.8680, 0.9125, 1.9233, 1.6076]],

        [[1.6108, 1.2400, 0.4745, 1.4094],
         [1.1775, 1.6323, 0.8564, 1.2352],
         [1.4318, 1.2586, 0.7968, 1.2816],
         [1.8968, 1.6363, 0.9437, 1.6900]],

        [[1.9214, 1.3171, 0.7165, 1.7967],
         [1.5782, 1.0342, 0.9042, 1.5412],
         [1.1326, 0.6626, 0.4557, 0.8929],
         [1.5490, 1.2542, 0.7185, 1.3425]]])
torch.Size([3, 4, 4])
