In [16]:
import torch
from torch.nn import functional as F

In [1]:
def verbose_attention(encoder_state_vectors, query_vector):
    """ 원소별 연산을 사용하는 어텐션 메커니즘 버전
    
    매개변수:
        encoder_state_vectors (torch.Tensor): 인코더의 양방향 GRU에서 출력된 3차원 텐서
        query_vector (torch.Tensor): 디코더 GRU의 은닉 상태
    """
    # TRY IT YOURSELF

def terse_attention(encoder_state_vectors, query_vector):
    """ 점곱을 사용하는 어텐션 메커니즘 버전
    
    매개변수:
        encoder_state_vectors (torch.Tensor): 인코더의 양방향 GRU에서 출력된 3차원 텐서
        query_vector (torch.Tensor): 디코더 GRU의 은닉 상태
    """
    # TRY IT YOURSELF

In [51]:
import numpy as np

np.random.seed(1234)
encoder_states = np.random.rand(3, 5, 4) # batch_size, num_vectors, vector_size
query_vector = encoder_states[:,-1, :]

encoder_states = torch.tensor(encoder_states)
query_vector = torch.tensor(query_vector)

context_vectors, vector_probabilities, vector_scores = verbose_attention(encoder_states, query_vector)
print(vector_probabilities.numpy())

context_vectors, vector_probabilities = terse_attention(encoder_states, query_vector)
print(vector_probabilities.numpy())

[[0.16908073 0.2026648  0.18250851 0.16886662 0.27687935]
 [0.12252482 0.24226674 0.17525572 0.15620217 0.30375056]
 [0.05641803 0.11084368 0.09659718 0.14712325 0.58901787]]
[[0.16908073 0.2026648  0.18250851 0.16886662 0.27687935]
 [0.12252482 0.24226674 0.17525572 0.15620217 0.30375056]
 [0.05641803 0.11084368 0.09659718 0.14712325 0.58901787]]
