In [3]:
import numpy as np

In [11]:
arr1 = np.array([2, 3, 5, 7])
arr2 = np.array([[4, 5, 6, 7],
                 [8, 9, 10, 11]])
arr3 = np.array([[[4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]]]*3)

In [12]:
print(arr1)
print(arr2)
print(arr3)

[2 3 5 7]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]]


In [13]:
arr3.shape

(3, 3, 4)

In [30]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.arange(3, 20, 3)

array([ 3,  6,  9, 12, 15, 18])

In [11]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indices = np.indices((3, 3))
print(array1[indices[0], indices[1]].diagonal())

[1 5 9]


In [12]:
print(array1.diagonal())

[1 5 9]


In [24]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
print(indices.shape)
print(indices)
print(indices[0])
print(indices[1])

(2, 3, 3)
[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]
[[0 0 0]
 [1 1 1]
 [2 2 2]]
[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [23]:
grid = np.indices((3, 5))
grid

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [31]:
grid.shape

(2, 3, 5)